// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAh1017KhHeaZ0YbcXk6EVWEm9hEAKdT8',
    appId: '1:474491838776:web:3abe96907d0b146af4a1cd',
    messagingSenderId: '474491838776',
    projectId: 'flutter-auth-4b3a3',
    authDomain: 'flutter-auth-4b3a3.firebaseapp.com',
    storageBucket: 'flutter-auth-4b3a3.appspot.com',
    measurementId: 'G-8NXS1RFHNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabZE0CMk7zQ2gp9PRIWkgXaG8O3pio8A',
    appId: '1:474491838776:android:83ae0d2eea3722fdf4a1cd',
    messagingSenderId: '474491838776',
    projectId: 'flutter-auth-4b3a3',
    storageBucket: 'flutter-auth-4b3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Lws23_zHpSFH0peWmmJbmobWU5zgkRA',
    appId: '1:474491838776:ios:3eab03adb6de54d9f4a1cd',
    messagingSenderId: '474491838776',
    projectId: 'flutter-auth-4b3a3',
    storageBucket: 'flutter-auth-4b3a3.appspot.com',
    iosClientId: '474491838776-i0b3jv0rnm9ssebdm117jd6sb8n3fvm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Lws23_zHpSFH0peWmmJbmobWU5zgkRA',
    appId: '1:474491838776:ios:77f51bbd69399ac6f4a1cd',
    messagingSenderId: '474491838776',
    projectId: 'flutter-auth-4b3a3',
    storageBucket: 'flutter-auth-4b3a3.appspot.com',
    iosClientId: '474491838776-jf41122qls782f52h6fnk45u9fi122rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
