// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1sXgQGTbWU64RlZf4pzB8juHwl5syHRc',
    appId: '1:241391269143:android:1896e7beb189592863b352',
    messagingSenderId: '241391269143',
    projectId: 'please-auth-382210',
    storageBucket: 'please-auth-382210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLuyW9T6AvFItpCH19i9BTDH67MqMVowI',
    appId: '1:241391269143:ios:4b5e7528129f5d5d63b352',
    messagingSenderId: '241391269143',
    projectId: 'please-auth-382210',
    storageBucket: 'please-auth-382210.appspot.com',
    androidClientId: '241391269143-2mp26qpmbgtdjt01oer22jg0hln377h9.apps.googleusercontent.com',
    iosClientId: '241391269143-ed7alk02arkvhk3r7tlt1t6om6akomf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
