// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMKEVsBbZG5Jo3PVHykeplB01O2csKms',
    appId: '1:370038842555:web:c4084de9b27a1e5f36b59e',
    messagingSenderId: '370038842555',
    projectId: 'flutter-auth-381504',
    authDomain: 'flutter-auth-381504.firebaseapp.com',
    storageBucket: 'flutter-auth-381504.appspot.com',
    measurementId: 'G-SMBQMYN1F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5uekp-Sic77GdPGbpj619bcmQq4UyS-8',
    appId: '1:370038842555:android:eb85a8b609b49a6836b59e',
    messagingSenderId: '370038842555',
    projectId: 'flutter-auth-381504',
    storageBucket: 'flutter-auth-381504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAccKdsqHUXKUsAVXzYQkSEmrbmLt-R5qQ',
    appId: '1:370038842555:ios:5b088d3a38fcce2736b59e',
    messagingSenderId: '370038842555',
    projectId: 'flutter-auth-381504',
    storageBucket: 'flutter-auth-381504.appspot.com',
    androidClientId: '370038842555-g6hta0b3a9e43pm5n3q00vo0jqc2400j.apps.googleusercontent.com',
    iosClientId: '370038842555-9t02dvg4jfll3bp7a2fipu9tlhv7jn9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAccKdsqHUXKUsAVXzYQkSEmrbmLt-R5qQ',
    appId: '1:370038842555:ios:8507c380ce5e034236b59e',
    messagingSenderId: '370038842555',
    projectId: 'flutter-auth-381504',
    storageBucket: 'flutter-auth-381504.appspot.com',
    androidClientId: '370038842555-g6hta0b3a9e43pm5n3q00vo0jqc2400j.apps.googleusercontent.com',
    iosClientId: '370038842555-0i4qkbmdnrk9eipu2498kk2v01fouuql.apps.googleusercontent.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}

